dataset: PROTEINS
task: graph_classification
model: GNN
hidden_dim: 64
num_hidden_layers: 4
layer_type: GIN
residual_connections: true
act_fn: ReLU
dropout: 0.0
loss_fn: CrossEntropyLoss
optimizer: Adam
scheduler: ReduceLROnPlateau
learning_rate: 0.001
batch_size: 64
max_epochs: 400
stopping_patience: 100
metric: acc
goal: max
wandb: false